[package]
name = "rustycry_v7"
version = "0.2.0"
edition = "2021"

[dependencies]
aes = "0.7"
block-modes = "0.8"
block-padding = "0.2"
walkdir = "2.3"
dirs = "4.0"
rand = "0.8"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

